#%RAML 1.0
title: Password Vault SAPI
version: 1.0
mediaType: application/json

securitySchemes:
  basic-auth: !include exchange_modules/org.mule.examples/basic-auth-securityscheme/1.0.0/basic-auth-securityscheme.raml

securedBy: basic-auth

/pvs/{jynx}:
  uriParameters:
    jynx:
      required: true
      example:
        value: anypoint
  get: 
   responses:
     200:
       body:
         application/json:
           example: {}